show_track:
    path: '/track/{id}'
    controller: 'App\Controller\TrackController::showTrack'

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
